ignore_merge_commits = true

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github"
owner = "quinnputer"
repository = "config"

[git_hooks]
commit-msg.path = "./.githooks/commit-msg.sh"
pre-commit.path = "./.githooks/pre-commit.sh"
